### Ping request
GET http://localhost:8080/ping

### Login
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=mongodb1@test.com&password=1234

### Ping Login with Barear token
GET http://localhost:8080/ping
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOiI2MWQ0MGQ2YjkxZGRiNDdmOThkOWQwZDMiLCJlbWFpbCI6Im1vbmdvZGIxQHRlc3QuY29tIiwicm9sZSI6IkZVTExfQUNDRVNTIn0.Mfcz4FCfqjYVd_EaVxH3k0jJhqc_QdYSCFOsARI6IRZV8PNE90flKD7e5dmsbtxnL3-5GbHV8LUzyflQE4xbfg


